const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavor')
const mindGrenade = require('./7-mind-grenade')
console.log(data)
console.log(names)
sayHi(names.john)
sayHi(names.peter)
sayHi("Susan")